-- Supabase SQL for blogs table
create table if not exists blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  content text not null,
  summary text,
  image_url text,
  published_at timestamptz default now(),
  updated_at timestamptz default now(),
  author text
);

-- Index for fast lookup
create index if not exists blogs_slug_idx on blogs(slug);
